# Based on https://github.com/aschmelyun/docker-compose-laravel
networks:
  metafilter:

services:
  app:
    build:
      context: ./docker
      dockerfile: Dockerfile.nginx
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    platform: linux/amd64
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html:delegated
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - redis
      - mysql
      - mailhog
    networks:
      - metafilter

  mysql:
    image: mysql:9
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    networks:
      - metafilter

  php:
    build:
      context: ./docker
      dockerfile: Dockerfile.php
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    platform: linux/amd64
    ports:
      - "9000:9000"
    volumes:
      - .:/var/www/html:delegated
    networks:
      - metafilter

  redis:
    image: redis:alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - metafilter

  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - metafilter

  composer:
    build:
      context: ./docker
      dockerfile: Dockerfile.php
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    volumes:
      - .:/var/www/html:delegated
    depends_on:
      - php
    entrypoint: [ 'composer', '--ignore-platform-reqs' ]
    profiles:
      - tools
    networks:
      - metafilter

  npm:
    image: node:current-alpine
    volumes:
      - .:/MetaFilter2024
      - node-modules:/MetaFilter2024/node_modules
    ports:
      - "3000:3000"
      - "3001:3001"
      - "5173:5173"
    working_dir: /MetaFilter2024
    entrypoint: [ 'npm' ]
    environment:
      - APP_HOST
      - VITE_HOST=0.0.0.0
    profiles:
      - tools
    networks:
      - metafilter

  artisan:
    build:
      context: ./docker
      dockerfile: Dockerfile.php
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    environment:
      - DB_HOST=mysql
      - DB_DATABASE
      - DB_USERNAME
      - DB_PASSWORD
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=8000
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www/html:delegated
    depends_on:
      - mysql
    entrypoint: [ 'php', '/var/www/html/artisan' ]
    profiles:
      - tools
    networks:
      - metafilter

volumes:
  node-modules:
